apiVersion: v1
kind: Secret
metadata:
  name: api-token
type: Opaque
data:
  token: YOUR_BASE64_ENCODED_TOKEN_HERE

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels:
      name: nodejs-app
  template:
    metadata:
      labels:
        name: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: YOUR_DOCKER_IMAGE_HERE
        ports:
        - containerPort: 3000
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: api-token
              key: token

