apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment-restored
  annotations:
    io.kubernetes.cri-o.annotations.checkpoint.name: "counter"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kubernetes.cri-o.annotations.checkpoint.name: counter 
  template:
    metadata:
      labels:
        io.kubernetes.cri-o.annotations.checkpoint.name: counter    
    spec:
      securityContext:
        fsGroup: 0
      imagePullSecrets:
        - name: docker.io
      containers:
        - name: counter
          image: markusfischer1/default_replicaset_counter-deployment_counter:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              COUNT=1;
              while true; do
                echo $(date) Count: $COUNT;
                COUNT=$((COUNT+1));
                sleep 1;
              done;

